<?php
/**
 * Vercel build step (run by vercel-php via `composer run vercel`).
 *
 * Downloads WordPress core into ./wordpress, then copies in our wp-config.php,
 * theme and plugin. Everything under ./wordpress is bundled into the function.
 */

$root    = dirname( __DIR__ );
$target  = $root . '/wordpress';
$version = getenv( 'WP_VERSION' ) ?: 'latest';
$url     = $version === 'latest'
	? 'https://wordpress.org/latest.tar.gz'
	: "https://wordpress.org/wordpress-{$version}.tar.gz";

function fail( string $msg ): void {
	fwrite( STDERR, "[wp-build] ERROR: {$msg}\n" );
	exit( 1 );
}

function rrmdir( string $dir ): void {
	if ( ! is_dir( $dir ) ) {
		return;
	}
	$it = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $dir, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::CHILD_FIRST
	);
	foreach ( $it as $file ) {
		$file->isDir() ? rmdir( $file->getPathname() ) : unlink( $file->getPathname() );
	}
	rmdir( $dir );
}

function rcopy( string $src, string $dst ): void {
	if ( ! is_dir( $src ) ) {
		fail( "missing source directory {$src}" );
	}
	@mkdir( $dst, 0755, true );
	$it = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $src, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::SELF_FIRST
	);
	foreach ( $it as $file ) {
		$dest = $dst . '/' . $it->getSubPathname();
		$file->isDir() ? @mkdir( $dest, 0755, true ) : copy( $file->getPathname(), $dest );
	}
}

/**
 * Runs a system command without the PHP runtime's LD_LIBRARY_PATH, whose bundled
 * libraries (e.g. an older libcurl) break system tools like curl.
 */
function system_cmd( string $cmd ): int {
	passthru( 'env -u LD_LIBRARY_PATH ' . $cmd, $code );
	return $code;
}

function download( string $url, string $dest, int $min_bytes = 100000 ): void {
	$data = @file_get_contents( $url );
	if ( $data !== false ) {
		file_put_contents( $dest, $data );
	} elseif ( system_cmd( 'curl -fsSL -o ' . escapeshellarg( $dest ) . ' ' . escapeshellarg( $url ) ) !== 0 ) {
		fail( "download failed: {$url}" );
	}
	clearstatcache();
	if ( ! is_file( $dest ) || filesize( $dest ) < $min_bytes ) {
		fail( "download looks truncated: {$url}" );
	}
}

// Scratch space inside the project: /tmp is on another device, so rename() into the project fails.
$work = $root . '/.wp-build';
rrmdir( $work );
mkdir( $work, 0755, true );

echo "[wp-build] Downloading WordPress ({$version}) from {$url}\n";
// Build-time PHP on Vercel runs without its extension modules (no zip), so extract with tar.
$archive = $work . '/wordpress.tar.gz';
download( $url, $archive, 1000000 );

rrmdir( $target );
if ( system_cmd( 'tar -xzf ' . escapeshellarg( $archive ) . ' -C ' . escapeshellarg( $work ) ) !== 0
	|| ! is_file( $work . '/wordpress/wp-settings.php' ) ) {
	fail( 'could not extract WordPress archive' );
}
if ( ! rename( $work . '/wordpress', $target ) ) {
	fail( "could not move WordPress into {$target}" );
}

// Drop bundled extras to keep the function bundle small.
foreach ( glob( $target . '/wp-content/themes/*', GLOB_ONLYDIR ) as $dir ) {
	rrmdir( $dir );
}
rrmdir( $target . '/wp-content/plugins/akismet' );
@unlink( $target . '/wp-content/plugins/hello.php' );

// Project code + config: every theme and plugin in the repo's wp-content.
foreach ( [ 'themes', 'plugins' ] as $type ) {
	foreach ( glob( $root . "/wp-content/{$type}/*", GLOB_ONLYDIR ) as $dir ) {
		rcopy( $dir, $target . "/wp-content/{$type}/" . basename( $dir ) );
	}
}
rcopy( __DIR__ . '/mu-plugins', $target . '/wp-content/mu-plugins' );
copy( __DIR__ . '/wp-config.php', $target . '/wp-config.php' );

// Salts: use env vars if set, otherwise generate per build so cookies can't be forged.
$salts = "<?php\n// Generated by vercel/build.php.\n";
foreach ( [ 'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT' ] as $key ) {
	$salts .= "define( '{$key}', " . var_export( getenv( $key ) ?: bin2hex( random_bytes( 32 ) ), true ) . " );\n";
}
file_put_contents( $target . '/wp-salts.php', $salts );

// Demo mode: no external database configured, so run on a bundled SQLite database.
if ( ! getenv( 'DB_HOST' ) ) {
	echo "[wp-build] DB_HOST not set: building demo site on SQLite\n";
	$plugins = $target . '/wp-content/plugins';
	$zipFile = $work . '/sqlite-plugin.zip';
	download( 'https://downloads.wordpress.org/plugin/sqlite-database-integration.latest-stable.zip', $zipFile );

	// Build-time PHP has no extensions loaded; run a child PHP with the runtime's php.ini (zip, pdo_sqlite).
	$php = escapeshellarg( PHP_BINARY )
		. ' -c ' . escapeshellarg( dirname( PHP_BINARY ) . '/php.ini' )
		. ' -d extension_dir=' . escapeshellarg( getenv( 'PHP_INI_EXTENSION_DIR' ) ?: dirname( PHP_BINARY ) . '/modules' );
	$unzip = sprintf( '$z = new ZipArchive(); if ($z->open(%s) !== true || !$z->extractTo(%s)) exit(1);', var_export( $zipFile, true ), var_export( $plugins, true ) );
	passthru( $php . ' -r ' . escapeshellarg( $unzip ), $code );
	if ( $code !== 0 ) {
		fail( 'could not extract the SQLite plugin' );
	}
	copy( $plugins . '/sqlite-database-integration/db.copy', $target . '/wp-content/db.php' );

	passthru( $php . ' ' . escapeshellarg( __DIR__ . '/seed-demo.php' ), $code );
	if ( $code !== 0 ) {
		fail( 'demo install failed' );
	}
}

rrmdir( $work );
echo "[wp-build] WordPress ready in {$target}\n";
