<?php
/**
 * Vercel build step (run by vercel-php via `composer run vercel`).
 *
 * Downloads WordPress core into ./wordpress, then copies in our wp-config.php,
 * theme and plugin. Everything under ./wordpress is bundled into the function.
 */

$root    = dirname( __DIR__ );
$target  = $root . '/wordpress';
$version = getenv( 'WP_VERSION' ) ?: 'latest';
$url     = $version === 'latest'
	? 'https://wordpress.org/latest.tar.gz'
	: "https://wordpress.org/wordpress-{$version}.tar.gz";

function fail( string $msg ): void {
	fwrite( STDERR, "[wp-build] ERROR: {$msg}\n" );
	exit( 1 );
}

function rrmdir( string $dir ): void {
	if ( ! is_dir( $dir ) ) {
		return;
	}
	$it = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $dir, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::CHILD_FIRST
	);
	foreach ( $it as $file ) {
		$file->isDir() ? rmdir( $file->getPathname() ) : unlink( $file->getPathname() );
	}
	rmdir( $dir );
}

function rcopy( string $src, string $dst ): void {
	if ( ! is_dir( $src ) ) {
		fail( "missing source directory {$src}" );
	}
	@mkdir( $dst, 0755, true );
	$it = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $src, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::SELF_FIRST
	);
	foreach ( $it as $file ) {
		$dest = $dst . '/' . $it->getSubPathname();
		$file->isDir() ? @mkdir( $dest, 0755, true ) : copy( $file->getPathname(), $dest );
	}
}

echo "[wp-build] Downloading WordPress ({$version}) from {$url}\n";
// Build-time PHP on Vercel runs without its extension modules (no zip/curl), so use curl + tar.
$archive = sys_get_temp_dir() . '/wordpress.tar.gz';
passthru( 'curl -fsSL -o ' . escapeshellarg( $archive ) . ' ' . escapeshellarg( $url ), $code );
if ( $code !== 0 ) {
	$data = @file_get_contents( $url );
	if ( $data === false ) {
		fail( "download failed: {$url}" );
	}
	file_put_contents( $archive, $data );
}
if ( filesize( $archive ) < 1000000 ) {
	fail( "download looks truncated: {$url}" );
}

rrmdir( $target );
$extractDir = sys_get_temp_dir() . '/wp-extract';
rrmdir( $extractDir );
mkdir( $extractDir, 0755, true );
passthru( 'tar -xzf ' . escapeshellarg( $archive ) . ' -C ' . escapeshellarg( $extractDir ), $code );
if ( $code !== 0 || ! is_file( $extractDir . '/wordpress/wp-settings.php' ) ) {
	fail( 'could not extract WordPress archive' );
}
rename( $extractDir . '/wordpress', $target );

// Drop bundled extras to keep the function bundle small.
foreach ( glob( $target . '/wp-content/themes/*', GLOB_ONLYDIR ) as $dir ) {
	rrmdir( $dir );
}
rrmdir( $target . '/wp-content/plugins/akismet' );
@unlink( $target . '/wp-content/plugins/hello.php' );

// Project code + config.
rcopy( $root . '/wp-content/themes/training-theme', $target . '/wp-content/themes/training-theme' );
rcopy( $root . '/wp-content/plugins/training-core', $target . '/wp-content/plugins/training-core' );
rcopy( __DIR__ . '/mu-plugins', $target . '/wp-content/mu-plugins' );
copy( __DIR__ . '/wp-config.php', $target . '/wp-config.php' );

// Salts: use env vars if set, otherwise generate per build so cookies can't be forged.
$salts = "<?php\n// Generated by vercel/build.php.\n";
foreach ( [ 'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT' ] as $key ) {
	$salts .= "define( '{$key}', " . var_export( getenv( $key ) ?: bin2hex( random_bytes( 32 ) ), true ) . " );\n";
}
file_put_contents( $target . '/wp-salts.php', $salts );

// Demo mode: no external database configured, so run on a bundled SQLite database.
if ( ! getenv( 'DB_HOST' ) ) {
	echo "[wp-build] DB_HOST not set: building demo site on SQLite\n";
	$plugins = $target . '/wp-content/plugins';
	$zipFile = sys_get_temp_dir() . '/sqlite-plugin.zip';
	passthru( 'curl -fsSL -o ' . escapeshellarg( $zipFile ) . ' https://downloads.wordpress.org/plugin/sqlite-database-integration.latest-stable.zip', $code );
	if ( $code !== 0 ) {
		fail( 'could not download the SQLite Database Integration plugin' );
	}

	// Build-time PHP has no extensions loaded; run a child PHP with the runtime's php.ini (zip, pdo_sqlite).
	$php = escapeshellarg( PHP_BINARY )
		. ' -c ' . escapeshellarg( dirname( PHP_BINARY ) . '/php.ini' )
		. ' -d extension_dir=' . escapeshellarg( getenv( 'PHP_INI_EXTENSION_DIR' ) ?: dirname( PHP_BINARY ) . '/modules' );
	$unzip = sprintf( '$z = new ZipArchive(); if ($z->open(%s) !== true || !$z->extractTo(%s)) exit(1);', var_export( $zipFile, true ), var_export( $plugins, true ) );
	passthru( $php . ' -r ' . escapeshellarg( $unzip ), $code );
	if ( $code !== 0 ) {
		fail( 'could not extract the SQLite plugin' );
	}
	copy( $plugins . '/sqlite-database-integration/db.copy', $target . '/wp-content/db.php' );

	passthru( $php . ' ' . escapeshellarg( __DIR__ . '/seed-demo.php' ), $code );
	if ( $code !== 0 ) {
		fail( 'demo install failed' );
	}
}

echo "[wp-build] WordPress ready in {$target}\n";
